### ISSUE TITLE
Base currency versus frontend currency

### ISSUE THREAD

**Issue by ebaschiera** [payfort/magento-payfort#1]
Hi,
I see that in PaymentController.php transactions are sent to PayFort in frontend currency, not in base currency. This is not good, because in Magento convention, the base currency is the currency used in transactions. Every payment method module use the base currency and base amount in transactions.
I believe this should be fixed.

Thank you.
Best regards.

-Ermanno Baschiera

**Comment by mohannadsaleh** [comment]
Hi , 
Thanks for your valuable feedback ,we have implemented the plugin this way in order to support merchants with multi MIDs to pass the currency they add in front to the FORT , 
we will keep enhancing the plugin and for sure this feedback will be taken into consideration , to add an option in the configuration either to pass the front currency or the base currency , without any extra coding , it will be just configuration under the FORT . 

Best Regards,

**Comment by ebaschiera** [comment]
Allright, thank you!
